### ISSUE TITLE
Unable to compile with 8.2

### ISSUE THREAD

**Issue by solskogen** [mist-devel/mist-firmware#20]
[solskogen@tenderheart mist-firmware]$ make
arm-none-eabi-gcc -I. -Iusb -DMIST -c -fno-common -O2 --std=gnu99 -fsigned-char -DVDATE=\"`date +"%y%m%d"`\"  -o syscalls.o -c syscalls.c
syscalls.c:26:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _system     _PARAMS ((const char *));
                     ^~~~~~~
syscalls.c:27:21: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _rename     _PARAMS ((const char *, const char *));
                     ^~~~~~~
syscalls.c:29:25: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     isatty          _PARAMS ((int));
                         ^~~~~~~
syscalls.c:30:26: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _isatty          _PARAMS ((int));
                          ^~~~~~~
syscalls.c:31:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 clock_t _times  _PARAMS ((struct tms *));
                 ^~~~~~~
syscalls.c:32:23: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _gettimeofday _PARAMS ((struct timeval *, struct timezone *));
                       ^~~~~~~
syscalls.c:33:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 void    _raise   _PARAMS ((void));
                  ^~~~~~~
syscalls.c:34:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _unlink  _PARAMS ((void));
                  ^~~~~~~
syscalls.c:35:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _link   _PARAMS ((void));
                 ^~~~~~~
syscalls.c:36:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _stat   _PARAMS ((const char *, struct stat *));
                 ^~~~~~~
syscalls.c:37:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _fstat   _PARAMS ((int, struct stat *));
                  ^~~~~~~
syscalls.c:38:16: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 caddr_t _sbrk  _PARAMS ((int));
                ^~~~~~~
syscalls.c:39:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _getpid  _PARAMS ((int));
                  ^~~~~~~
syscalls.c:40:16: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _kill  _PARAMS ((int, int));
                ^~~~~~~
syscalls.c:41:16: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 void    _exit  _PARAMS ((int));
                ^~~~~~~
syscalls.c:42:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _close  _PARAMS ((int));
                 ^~~~~~~
syscalls.c:43:19: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _swiclose _PARAMS ((int));
                   ^~~~~~~
syscalls.c:44:16: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _open  _PARAMS ((const char *, int, ...));
                ^~~~~~~
syscalls.c:45:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _swiopen _PARAMS ((const char *, int));
                  ^~~~~~~
syscalls.c:46:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _write   _PARAMS ((int, char *, int));
                  ^~~~~~~
syscalls.c:47:19: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _swiwrite _PARAMS ((int, char *, int));
                   ^~~~~~~
syscalls.c:48:17: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _lseek  _PARAMS ((int, int, int));
                 ^~~~~~~
syscalls.c:49:19: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _swilseek _PARAMS ((int, int, int));
                   ^~~~~~~
syscalls.c:50:16: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _read  _PARAMS ((int, char *, int));
                ^~~~~~~
syscalls.c:51:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 int     _swiread _PARAMS ((int, char *, int));
                  ^~~~~~~
syscalls.c:52:36: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 void    initialise_monitor_handles _PARAMS ((void));
                                    ^~~~~~~
syscalls.c:54:18: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 static int wrap  _PARAMS ((int));
                  ^~~~~~~
syscalls.c:55:19: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 static int error  _PARAMS ((int));
                   ^~~~~~~
syscalls.c:56:22: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 static int get_errno _PARAMS ((void));
                      ^~~~~~~
syscalls.c:57:25: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 static int remap_handle _PARAMS ((int));
                         ^~~~~~~
syscalls.c:58:24: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 static int do_AngelSWI _PARAMS ((int, void *));
                        ^~~~~~~
syscalls.c:59:22: error: expected '=', ',', ';', 'asm' or '__attribute__' before '_PARAMS'
 static int  findslot _PARAMS ((int));
                      ^~~~~~~
syscalls.c:66:30: error: expected ')' before '(' token
 extern void   _EXFUN(__sinit,(struct _reent *));
                              ^
                              )
syscalls.c: In function 'remap_handle':
syscalls.c:71:2: warning: implicit declaration of function '__sinit'; did you mean 'spi_init'? [-Wimplicit-function-declaration]
  __sinit (ptr);    \
  ^~~~~~~
syscalls.c:128:3: note: in expansion of macro 'CHECK_INIT'
   CHECK_INIT(_REENT);
   ^~~~~~~~~~
make: *** [Makefile:80: syscalls.o] Error 1

[solskogen@tenderheart mist-firmware]$ arm-none-eabi-gcc -v
Using built-in specs.
COLLECT_GCC=arm-none-eabi-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-none-eabi/8.2.0/lto-wrapper
Target: arm-none-eabi
Configured with: /build/arm-none-eabi-gcc/src/gcc-8.2.0/configure --target=arm-none-eabi --prefix=/usr --with-sysroot=/usr/arm-none-eabi --with-native-system-header-dir=/include --libexecdir=/usr/lib --enable-languages=c,c++ --enable-plugins --disable-decimal-float --disable-libffi --disable-libgomp --disable-libmudflap --disable-libquadmath --disable-libssp --disable-libstdcxx-pch --disable-nls --disable-shared --disable-threads --disable-tls --with-gnu-as --with-gnu-ld --with-system-zlib --with-newlib --with-headers=/usr/arm-none-eabi/include --with-python-dir=share/gcc-arm-none-eabi --with-gmp --with-mpfr --with-mpc --with-isl --with-libelf --enable-gnu-indirect-function --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --with-pkgversion='Arch Repository' --with-bugurl=https://bugs.archlinux.org/ --with-multilib-list=rmprofile
Thread model: single
gcc version 8.2.0 (Arch Repository)

**Comment by gyurco** [comment]
Fixed
